services:
  - type: web
    name: reco
    runtime: node
    plan: free
    buildCommand: npm ci --include=dev && npm run build
    startCommand: npm start
    pullRequestPreviewsEnabled: true
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
